version: 2
registries:
  artifactory:
    rubygems-server-pkgs-shopify-io:
    type: rubygems-server
    url: https://pkgs.shopify.io
    username: ${{secrets.RUBYGEMS_SERVER_PKGS_SHOPIFY_IO_USERNAME}}
    password: ${{secrets.RUBYGEMS_SERVER_PKGS_SHOPIFY_IO_PASSWORD}}
updates:
  - package-ecosystem: "bundler"
    vendor: true
    directory: "/"
    registries:
      - artifactory
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct" # only explicitly defined dependencies.
